# Generated by Django 4.2.7 on 2026-02-04 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="菜单名称")),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="图标样式"
                    ),
                ),
                ("path", models.CharField(max_length=255, verbose_name="前端路由路径")),
                (
                    "component",
                    models.CharField(max_length=255, verbose_name="前端组件路径"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "permission_code",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="权限标识码"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="admin_management.menu",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统菜单",
                "db_table": "admin_menu",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="AdminRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_name", models.CharField(max_length=64, verbose_name="角色名称")),
                (
                    "role_key",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        verbose_name="角色标识(如 super_admin)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "menus",
                    models.ManyToManyField(
                        blank=True,
                        to="admin_management.menu",
                        verbose_name="拥有的菜单权限",
                    ),
                ),
            ],
            options={
                "verbose_name": "管理角色",
                "db_table": "admin_role",
            },
        ),
    ]
