# Generated by Django 4.2.7 on 2026-02-04 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminrole",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="admin_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="关联用户",
            ),
        ),
    ]
