# Generated by Django 5.2.9 on 2026-02-05 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_management", "0002_adminrole_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator_name",
                    models.CharField(
                        help_text="防止用户删除后无法追溯",
                        max_length=64,
                        verbose_name="操作人快照",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("POST", "新增"),
                            ("PUT", "修改"),
                            ("PATCH", "部分修改"),
                            ("DELETE", "删除"),
                        ],
                        max_length=10,
                        verbose_name="请求方法",
                    ),
                ),
                ("path", models.CharField(max_length=255, verbose_name="请求路径")),
                (
                    "module",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="功能模块"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(null=True, verbose_name="IP地址"),
                ),
                ("body", models.JSONField(default=dict, verbose_name="请求参数")),
                (
                    "response_code",
                    models.IntegerField(default=200, verbose_name="响应状态码"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "db_table": "admin_audit_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
