# Generated by Django 5.2.9 on 2026-02-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_management", "0004_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="如: daily_reward_points",
                        max_length=64,
                        unique=True,
                        verbose_name="配置键名",
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="如果是JSON或列表，请存为字符串格式",
                        verbose_name="配置值",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="配置说明"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="若为True，可被小程序端接口获取",
                        verbose_name="是否公开",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统配置",
                "db_table": "sys_config",
                "ordering": ["key"],
            },
        ),
    ]
