# Generated by Django 4.2.7 on 2026-01-05 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(0, "未知"), (1, "男"), (2, "女")],
                        default=0,
                        verbose_name="性别",
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        help_text="单位: cm", null=True, verbose_name="身高"
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        help_text="单位: kg", null=True, verbose_name="体重"
                    ),
                ),
                ("age", models.IntegerField(null=True, verbose_name="年龄")),
                (
                    "activity_level",
                    models.FloatField(default=1.2, verbose_name="活动系数"),
                ),
                (
                    "daily_kcal_limit",
                    models.IntegerField(default=2000, verbose_name="每日热量目标"),
                ),
                (
                    "diet_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='偏好标签，例如: ["减脂", "辣", "低碳"]',
                        verbose_name="饮食偏好",
                    ),
                ),
                (
                    "allergens",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='过敏源列表，例如: ["花生", "海鲜"]',
                        verbose_name="过敏源",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户画像",
                "verbose_name_plural": "用户画像",
                "db_table": "users_profile",
            },
        ),
    ]
