# Generated by Django 4.2.7 on 2026-01-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "身体档案"},
        ),
        migrations.AddField(
            model_name="profile",
            name="goal_type",
            field=models.CharField(
                choices=[("lose", "减脂"), ("maintain", "保持"), ("gain", "增肌")],
                default="maintain",
                max_length=10,
                verbose_name="健康目标",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="activity_level",
            field=models.FloatField(default=1.2, help_text="1.2~1.9"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name="profile",
            name="allergens",
            field=models.JSONField(blank=True, default=list, verbose_name="过敏源"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="daily_kcal_limit",
            field=models.IntegerField(default=2000, verbose_name="每日推荐摄入"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="diet_tags",
            field=models.JSONField(
                blank=True, default=list, verbose_name="饮食偏好标签"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.SmallIntegerField(choices=[(1, "男"), (2, "女")], default=1),
        ),
        migrations.AlterField(
            model_name="profile",
            name="height",
            field=models.FloatField(default=170, help_text="cm"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="weight",
            field=models.FloatField(default=65, help_text="kg"),
        ),
    ]
