# Generated by Django 4.2.7 on 2026-01-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_options_profile_goal_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/%Y/%m/", verbose_name="头像"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="bmr",
            field=models.IntegerField(default=0, verbose_name="基础代谢率"),
        ),
        migrations.AddField(
            model_name="profile",
            name="signature",
            field=models.TextField(blank=True, null=True, verbose_name="个性签名"),
        ),
        migrations.AddField(
            model_name="profile",
            name="target_weight",
            field=models.FloatField(blank=True, null=True, verbose_name="目标体重(kg)"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="goal_type",
            field=models.CharField(
                choices=[("lose", "减脂"), ("maintain", "保持"), ("gain", "增肌")],
                default="maintain",
                max_length=20,
                verbose_name="健康目标",
            ),
        ),
    ]
