# Generated by Django 4.2.7 on 2026-01-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_avatar_profile_bmr_profile_signature_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.SmallIntegerField(
                choices=[(0, "未知"), (1, "男"), (2, "女")],
                default=0,
                verbose_name="性别",
            ),
        ),
    ]
