# Generated by Django 5.2.9 on 2026-03-16 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_profile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="water_goal_cups",
            field=models.IntegerField(default=8, verbose_name="每日饮水目标(杯)"),
        ),
        migrations.CreateModel(
            name="UserFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="关注时间"),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_rels",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关注者",
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_rels",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="被关注者",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户关注",
                "db_table": "users_userfollow",
                "unique_together": {("follower", "following")},
            },
        ),
    ]
