# Generated by Django 4.2.7 on 2026-04-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_profile_water_goal_cups_userfollow"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="water_goal_ml",
            field=models.IntegerField(default=2000, verbose_name="每日饮水目标(ml)"),
        ),
    ]
