# Generated by Django 5.2.9 on 2026-04-07 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_profile_water_goal_ml"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfollow",
            options={"verbose_name": "关注关系", "verbose_name_plural": "关注关系"},
        ),
        migrations.AlterUniqueTogether(
            name="userfollow",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userfollow",
            name="followed",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follower_relationships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="被关注者",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userfollow",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userfollow",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following_relationships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="关注者",
            ),
        ),
        migrations.AlterModelTable(
            name="userfollow",
            table="users_user_follow",
        ),
        migrations.RemoveField(
            model_name="userfollow",
            name="following",
        ),
        migrations.AlterUniqueTogether(
            name="userfollow",
            unique_together={("follower", "followed")},
        ),
    ]
