# Generated by Django 4.2.7 on 2026-01-26 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=32, verbose_name="运动类型")),
                ("duration", models.IntegerField(verbose_name="时长(分钟)")),
                ("calories_burned", models.IntegerField(verbose_name="消耗热量")),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="日期"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "运动记录",
                "db_table": "diet_workoutrecord",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyIntake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_date",
                    models.DateField(
                        auto_now_add=True, db_index=True, verbose_name="记录日期"
                    ),
                ),
                (
                    "meal_time",
                    models.CharField(
                        choices=[
                            ("breakfast", "早餐"),
                            ("lunch", "午餐"),
                            ("dinner", "晚餐"),
                            ("snack", "加餐"),
                            ("night_snack", "夜宵"),
                        ],
                        default="lunch",
                        max_length=20,
                        verbose_name="餐次",
                    ),
                ),
                (
                    "exact_time",
                    models.TimeField(blank=True, null=True, verbose_name="用餐时间"),
                ),
                (
                    "source_type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "自制(菜谱)"),
                            (2, "外卖(商家)"),
                            (3, "自定义录入"),
                        ],
                        verbose_name="来源类型",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True,
                        help_text="关联 MongoDB 中的 ID",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "food_name",
                    models.CharField(max_length=128, verbose_name="食物名称"),
                ),
                (
                    "calories",
                    models.IntegerField(default=0, verbose_name="卡路里(kcal)"),
                ),
                (
                    "macros",
                    models.JSONField(
                        default=dict,
                        help_text='{"carbohydrates": 12.0, "protein": 8.0, "fat": 10.0}',
                        verbose_name="宏量营养素",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intake_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "饮食记录",
                "db_table": "diet_dailyintake",
                "ordering": ["-record_date", "meal_time", "id"],
            },
        ),
        migrations.CreateModel(
            name="WeightRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="记录日期"
                    ),
                ),
                ("weight", models.FloatField(verbose_name="体重(kg)")),
                ("bmi", models.FloatField(blank=True, null=True, verbose_name="BMI")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "diet_weightrecord",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_id",
                    models.CharField(help_text="MongoDB中的ID", max_length=64),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("recipe", "菜谱"), ("restaurant", "餐厅")],
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("like", "收藏/喜欢"), ("block", "拉黑/不吃")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "diet_userpreference",
                "indexes": [
                    models.Index(
                        fields=["user", "action"], name="diet_userpr_user_id_ddfbfa_idx"
                    )
                ],
                "unique_together": {("user", "target_id", "action")},
            },
        ),
        migrations.CreateModel(
            name="FridgeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="食材名称"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="分类"
                    ),
                ),
                (
                    "quantity",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="数量描述"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="过期日期"),
                ),
                (
                    "is_scrap",
                    models.BooleanField(default=False, verbose_name="是否边角料"),
                ),
                ("amount", models.FloatField(default=1.0, verbose_name="数量数值")),
                (
                    "sub_category",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="子分类"
                    ),
                ),
                (
                    "unit",
                    models.CharField(default="个", max_length=10, verbose_name="单位"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="入库时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fridge_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "冰箱食材",
                "db_table": "diet_fridgeitem",
                "indexes": [
                    models.Index(
                        fields=["user", "name"], name="diet_fridge_user_id_1e2d2a_idx"
                    ),
                    models.Index(
                        fields=["expiry_date"], name="diet_fridge_expiry__283bf6_idx"
                    ),
                ],
            },
        ),
    ]
