# Generated by Django 4.2.7 on 2026-01-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="任务标题")),
                ("desc", models.CharField(max_length=255, verbose_name="任务描述")),
                (
                    "reward_points",
                    models.IntegerField(default=10, verbose_name="奖励积分"),
                ),
                (
                    "task_type",
                    models.CharField(
                        default="daily", max_length=20, verbose_name="类型"
                    ),
                ),
                (
                    "condition_code",
                    models.CharField(max_length=64, verbose_name="条件代码"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
            ],
            options={
                "verbose_name": "挑战任务",
                "db_table": "diet_challengetask",
            },
        ),
        migrations.CreateModel(
            name="Remedy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scenario",
                    models.CharField(
                        choices=[
                            ("overeat", "暴食"),
                            ("stay_up", "熬夜"),
                            ("constipation", "便秘"),
                            ("hangover", "宿醉"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="场景",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="方案标题")),
                ("desc", models.TextField(verbose_name="方案详情")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "补救方案",
                "db_table": "diet_remedy",
                "ordering": ["order"],
            },
        ),
    ]
