# Generated by Django 5.2.9 on 2026-03-16 03:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0003_achievement_userachievement_userchallengeprogress_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="category",
            field=models.CharField(
                choices=[
                    ("daily", "每日"),
                    ("weekly", "每周"),
                    ("monthly", "每月"),
                    ("special", "特殊"),
                ],
                default="special",
                max_length=32,
                verbose_name="分类",
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="points",
            field=models.IntegerField(default=10, verbose_name="积分"),
        ),
        migrations.AddField(
            model_name="achievement",
            name="rarity",
            field=models.CharField(
                choices=[("common", "普通"), ("rare", "稀有"), ("epic", "史诗")],
                default="common",
                max_length=32,
                verbose_name="稀有度",
            ),
        ),
        migrations.CreateModel(
            name="UserFeaturedBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序序号")),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diet.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "个性名片代表徽章",
                "db_table": "diet_userfeaturedbadge",
                "ordering": ["sort_order"],
                "unique_together": {("user", "achievement")},
            },
        ),
        migrations.CreateModel(
            name="WaterIntake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="日期"
                    ),
                ),
                ("cups", models.IntegerField(default=0, verbose_name="杯数")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "饮水记录",
                "db_table": "diet_waterintake",
                "unique_together": {("user", "date")},
            },
        ),
    ]
