# Generated by Django 4.2.7 on 2026-04-01 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0004_achievement_category_achievement_points_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="waterintake",
            name="cups",
        ),
        migrations.AddField(
            model_name="waterintake",
            name="food_ml",
            field=models.IntegerField(default=0, verbose_name="食物水分(ml)"),
        ),
        migrations.AddField(
            model_name="waterintake",
            name="manual_ml",
            field=models.IntegerField(default=0, verbose_name="手动饮水(ml)"),
        ),
        migrations.AddField(
            model_name="waterintake",
            name="total_ml",
            field=models.IntegerField(default=0, verbose_name="总饮水(ml)"),
        ),
        migrations.CreateModel(
            name="WaterEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ml", models.IntegerField(verbose_name="变动毫升")),
                (
                    "source",
                    models.CharField(
                        default="manual", help_text="manual / reset 等", max_length=20
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="附加备注"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发生时间"),
                ),
                (
                    "intake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="diet.waterintake",
                    ),
                ),
            ],
            options={
                "verbose_name": "饮水事件详情",
                "db_table": "diet_waterevent",
            },
        ),
    ]
