# Generated by Django 5.2.9 on 2026-04-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0007_expand_remedy_admin_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfeaturedbadge",
            options={"ordering": ["sort_order"], "verbose_name": "用户展示徽章"},
        ),
        migrations.AlterField(
            model_name="achievement",
            name="icon",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="图标 URL"
            ),
        ),
        migrations.AlterField(
            model_name="challengetask",
            name="task_type",
            field=models.CharField(
                default="daily", max_length=20, verbose_name="任务类型"
            ),
        ),
        migrations.AlterField(
            model_name="remedy",
            name="points_cost",
            field=models.IntegerField(default=10, verbose_name="扣除积分"),
        ),
        migrations.AlterField(
            model_name="remedy",
            name="scenario",
            field=models.CharField(
                choices=[
                    ("overeat", "暴饮暴食"),
                    ("stay_up", "熬夜"),
                    ("miss_workout", "缺乏运动"),
                    ("low_water", "饮水不足"),
                    ("constipation", "便秘"),
                    ("hangover", "宿醉"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="场景",
            ),
        ),
    ]
